name: Testing Suite

on:
  pull_request:
    branches: 
      - main
      - dev

jobs:
  test:
    name: Testing our application against our testing suite.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: npm install and test
      run: |
        npm install
        npm test
